### ISSUE TITLE
request for your code

### ISSUE THREAD

**Issue by stvsd1314** [donald323/FLCPID-vs-DRLPID#2]
hello. i can not see your code

**Comment by donald323** [comment]
I am still working on tweaking the codes, I will upload them as soon as possible. (Thank you for letting me know that there are people interested in this topic, I thought no one would be interested)

**Comment by donald323** [comment]
> hello. i can not see your code

I have just uploaded the libraries needed for constructing the ship simulator, I will upload on the Fuzzy Logic/Deep Reinforcement learning implementation later.

**Comment by stvsd1314** [comment]
Thanks for your replay. A excellent work！



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 17, 2022 17:26 PM
To: ***@***.***&gt;;
Cc: "steven ***@***.******@***.***&gt;;
Subject: Re: [donald323/FLCPID-vs-DRLPID] request for your code (Issue #2)




  
hello. i can not see your code
  
I have just uploaded the libraries needed for constructing the ship simulator, I will upload on the Fuzzy Logic/Deep Reinforcement learning implementation later.

**Comment by donald323** [comment]
All codes have been uploaded.
